[project]
name = "week-2"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "fastmcp>=3.2.4",
    "google-genai>=1.75.0",
    "google-generativeai>=0.8.6",
    "ollama>=0.6.2",
    "python-dotenv>=1.2.2",
    "ruff>=0.15.12",
]
